Feladat #1 - Init
Teaching-projects/SZE-MOSZE-2020-plusplusplus pull request #1
Opened 2020-09-09 14:39 UTC by bencebaranyai

- [ ]  Readme fájl frissítve
- [ ]  Alap kimenetet adó paraméterezhető program
- [ ]  .gitignore a build / ide fájlok kizárására
- [ ]  Tesztelve Linuxon, Windowson

2020-09-13 10:59 UTC, oliverosz requested changes

2020-09-13 10:59 UTC, oliverosz commented on loop.cpp
> +        this->players[i].Read(argv, i);
A paraméterek feldolgozása nem a Player feladata. A jellemzőit a konstruktorban kellene átadni az inicializáláshoz.

2020-09-13 10:59 UTC, oliverosz commented on loop.cpp
> +	return this->currentPlayer + 1 < NUMBER_OF_PLAYERS ? this->currentPlayer + 1 : 0;
Egyszerűbben: `return this->currentPlayer + 1 % NUMBER_OF_PLAYERS;`

2020-09-13 10:59 UTC, oliverosz commented on player.cpp
> +    otherPlayer->hp = otherPlayer->hp - this->damage;
egyszerűbben: `otherPlayer->hp -= this->damage;`

2020-09-13 10:59 UTC, oliverosz commented on player.h
> +    void Print();
Ezek a függvények legyenek constok. A Loopban szintén, ami lehet const, legyen az.

2020-09-13 10:59 UTC, oliverosz commented on loop.cpp
> +    this->players = new Player[NUMBER_OF_PLAYERS]();
Hol van felszabadítva az itt lefoglalt memória?

2020-09-13 10:59 UTC, oliverosz commented on loop.cpp
> +    std::cout << '\n';
A `ShowPlayers`ben kellene sortörést tenni a kiíratás végére.

2020-09-13 19:14 UTC, bencebaranyai commented
@oliverosz javítottuk az észrevételeket.
A játékosokat `std::vector`-ban tároljuk mostantól, a `Player` konstruktorból már a jellemzőit kapja.
A kiírató és lekérdező függvények konstansok.

2020-09-13 22:37 UTC, oliverosz requested changes
Ismétlem, a Loop megfelelő tagfüggvényei is legyenek constok.

2020-09-13 22:37 UTC, oliverosz commented on player.cpp
> +    this->damage = damage;
Ezt inicializáló listával kéne megoldani.

2020-09-13 22:37 UTC, oliverosz commented on player.h
> +    explicit Player(std::string name, unsigned short hp, unsigned short damage);
A név másolása felesleges, az objektumokat const referenciaként adjuk át.

2020-09-13 22:37 UTC, oliverosz commented on loop.cpp
> +    for (auto player : this->players)
Itt is const referenciát kellene használni, hogy ne másolódjanak feleslegesen a Playerek.

2020-09-13 22:37 UTC, oliverosz commented on loop.cpp
> +        this->players.push_back(this->getPlayer(argv, i));
A vector használata jó megoldás. Egy apróság: mivel itt jönnek létre a Playerek, az `emplace_back` használata helyesebb lenne.

2020-09-13 22:37 UTC, oliverosz commented on player.h
> +    std::string GetName() const { return name; };
Visszatérési értékben is inkább const referencia legyen. És az attack nem lett const, pedig lehetne.

2020-09-13 22:37 UTC, oliverosz commented on loop.cpp
> +    return (this->currentPlayer + 1) % 2;
Hupsz, a zárójelet valóban lehagytam. Viszont miért lett a `NUMBER_OF_PLAYERS`ből `2`?

2020-09-14 20:46 UTC, oliverosz approved these changes
Ok, @hegyhati mehet a merge

2020-09-15 13:43 UTC, merged