Jsonparser
Teaching-projects/SZE-MOSZE-2020-plusplusplus pull request #10
Opened 2020-10-12 08:54 UTC by bencebaranyai

JSON parser class added with unit tests.

Closes #6

2020-10-14 07:50 UTC, wajzy requested changes
Csak annyit kérek, hogy a parzoló osztály használata legyen egyértelműbb: derüljön ki a fv. nevéből, hogy mire szolgál! Pl. parseString, ha egy stringet akarok elemezni, és ne legyen kevert feladata egy-egy fv.-nek!

2020-10-14 07:50 UTC, wajzy commented on json.cpp
> +std::map<std::string, std::any> Json::ParseJson(const std::string &inputOrFile)
Ne keverd össze a funkciókat! Legyenek külön tagfüggvények a háromféle eltérő típusú bemenet kezelésére!

2020-10-14 07:50 UTC, wajzy commented on json.cpp
> +    static const std::regex jsonParseRegex("\\s*\"([a-z]*)\"\\s*:\\s*([0-9]*\\.?[0-9]+|\"[\\w\\s]*\")\\s*[,}]\\s*");
Nagyjából jó, bár ha } helyett ,-vel fejeződik be...

2020-10-14 09:36 UTC, bencebaranyai commented
@wajzy 
Javítottam az érszrevételeket, a függvényeket átneveztem.
És további `jsonParseError`-t dob a parser, ha , helyett } van, vagy ha egyéb hiba van az adatban.

2020-10-22 18:39 UTC, wajzy approved these changes

2020-10-22 18:39 UTC, wajzy commented
@karcagtamas Oldd fel az ütközéseket!

2020-10-22 18:53 UTC, bencebaranyai commented
> @karcagtamas Oldd fel az ütközéseket!

@wajzy Rebase-eltem masterre.

2020-10-24 17:14 UTC, merged