Makefile
Teaching-projects/SZE-MOSZE-2020-plusplusplus pull request #17
Opened 2020-10-31 14:16 UTC by Cerberuuus

Elkészült a Makefile és a hozzá tartozó módosítások.

Closes #13.

2020-10-31 19:42 UTC, hegyhati requested changes

2020-10-31 19:42 UTC, hegyhati commented on Makefile
> +	$(CC) $(CFLAGS) -c loop.cpp
ha a player hasznalja a json-t, akkor az ide is kell

2020-10-31 19:42 UTC, hegyhati commented on Makefile
> +json.o: json.cpp json.h jsonFileReadError.h jsonParseError.h
es akkor ezek az error headerek is kellenek mindenhova.

2020-10-31 23:55 UTC, Cerberuuus commented
Pótoltam a hiányosságot.

2020-11-01 14:04 UTC, Cerberuuus commented
Javítottam még néhány dolgot @hegyhati.

2020-11-01 23:57 UTC, hegyhati approved these changes

2020-11-01 23:57 UTC, merged