Renderer
Teaching-projects/SZE-MOSZE-2020-plusplusplus pull request #38
Opened 2020-12-05 19:04 UTC by bencebaranyai

Closes #34

2020-12-05 19:40 UTC, karcagtamas requested changes

2020-12-05 19:40 UTC, karcagtamas commented on renderer/Renderer.h
> +};
Hiányzó dokumentáció

2020-12-06 20:15 UTC, karcagtamas approved these changes

2020-12-06 20:21 UTC, Cerberuuus commented on Game.cpp
> +			return monster.getTexture();
Itt a monster lehetne referencia alapú és a getLocation-nél hiányzik a const quailifier.

2020-12-06 20:36 UTC, Cerberuuus approved these changes

2020-12-06 21:39 UTC, karcagtamas approved these changes

2020-12-06 21:50 UTC, Cerberuuus approved these changes

2020-12-08 10:53 UTC, Jabezare approved these changes

2020-12-08 10:58 UTC, merged