Levelup
Teaching-projects/SZE-MOSZE-2020-plusplusplus pull request #9
Opened 2020-10-11 20:57 UTC by Cerberuuus

Levelup issues have been resolved.

Closes #5 .

2020-10-12 09:22 UTC, oliverosz requested changes
Az SCA és a leak check rendben van. A kódban néhány apróságot kell még javítani.

2020-10-12 09:22 UTC, oliverosz commented on player.cpp
> +    }
Egy ütéstől akár több szintet is léphet. (Amúgy ha az xp-t így kumulálva tároljátok és nem az utolsó szintlépés óta szerzett xp-t, akkor fölösleges külön tárolni a szintet, mert a fenti képlettel bármikor kiszámítható az xp-ből.)

2020-10-12 09:22 UTC, oliverosz commented on player.h
> +    void levelUp(unsigned short newLevel);
Ezek a metódusok ne legyenek publikusak.

2020-10-12 09:22 UTC, oliverosz commented on player.h
> +    unsigned short maxHp;
A `name` legyen const.

2020-10-12 20:08 UTC, oliverosz requested changes
Ok, most már jó a megoldás. Viszont mivel közben be lett mergelve egy másik branch a masterbe, most ezt a branchet frissíteni kell a masterre, és feloldani a konfliktusokat, mielőtt ezt is be lehetne mergelni.

2020-10-14 13:09 UTC, oliverosz requested changes
Hát egy kicsit kavaros lett ez a merge. Közben az attackspeed logikája is módosult, amit nem indokolt a levelup logikája, de nagyjából rendben van, főleg csak dokumentációs hiányosságok vannak.

2020-10-14 13:09 UTC, oliverosz commented on .gitignore
> +*.txt
Mivel már be lettek commitolva txt-k, azokat utólag ki kell törölni a repóból.

2020-10-14 13:09 UTC, oliverosz commented on player.cpp
> +#include <math.h>
`cmath`

2020-10-14 13:09 UTC, oliverosz commented on player.h
> +    float nextAttack = 0;
A "Count of the attacks" az miért `float`?

2020-10-14 13:09 UTC, oliverosz commented on player.h
> +    const short GetLevel() const { return (xp / LEVEL_SIZE) + 1; };
Ez még mindig TODO :)

2020-10-14 13:09 UTC, oliverosz commented on player.h
> +    void levelUp(unsigned short newLevel);
doc missing

2020-10-14 13:09 UTC, oliverosz commented on player.cpp
> +    this->increaseXP(this->damage);
Fatality esetén nem kéne a teljes dmg-ért megkapni az xp-t, csak amennyit sebezni tudott.

2020-10-14 13:09 UTC, oliverosz commented on player.h
> +    float getNextAttack() { return nextAttack; };
`const`

2020-10-14 16:38 UTC, karcagtamas commented on player.h
> +    const short GetLevel() const { return (xp / LEVEL_SIZE) + 1; };
A megjelölt hiányoságok többségéhez hasonlóan, ezt még nem csináltuk meg. A tegnapi rebase után nem jutott idő mindenre. Mihamarabb pótoljuk őket.

2020-10-14 16:43 UTC, karcagtamas commented on player.h
> +    float nextAttack = 0;
Az attackspeed logikának kicsit változni kelett, mivel volt a feladat listában egy olyan kikötés, hogy szintlépéskor az attackcooldown-nak csökkenie kell, viszont a "régi" megoldás ezt a módosítást nem támogatta megfelelően.

2020-10-16 17:16 UTC, oliverosz approved these changes

2020-10-16 17:16 UTC, oliverosz commented on player.cpp
> +    this->increaseXP(damageAmount);
OK, ez már jó így. A HP csökkentését is ki lehetett volna így emelni, de nem baj. (`otherPlayer->hp -= damageAmount`)

2020-10-16 17:16 UTC, merged